# Generated by Django 4.2.7 on 2025-04-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horticulture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='conditions_favoring',
            field=models.TextField(blank=True, help_text='Conditions favoring disease development', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='geographic_distribution',
            field=models.TextField(blank=True, help_text='Geographic distribution of the disease', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='transmission_methods',
            field=models.JSONField(blank=True, default=list, help_text='Array of transmission methods'),
        ),
    ]
