# Generated by Django 5.2 on 2025-04-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "horticulture",
            "0002_companionplantinginteraction_alter_region_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companionship",
            unique_together=set(),
        ),
    ]
