# Generated by Django 5.2 on 2025-04-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("horticulture", "0003_alter_companionship_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companionship",
            unique_together={("plant_subject", "plant_object")},
        ),
    ]
