# Generated by Django 5.2 on 2025-04-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horticulture', '0004_alter_companionship_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='zone_identifier',
            field=models.CharField(default='Unknown', help_text="The specific zone identifier within the system (e.g., '7a', '9b')", max_length=20),
        ),
        migrations.AlterField(
            model_name='soilprofile',
            name='name',
            field=models.CharField(default='Default Soil Profile', help_text="Unique name for the soil profile (e.g., 'Generic Clay Loam')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='fertilizer_name',
            field=models.CharField(default='Unknown Fertilizer', help_text='Name of the fertilizer', max_length=150),
        ),
        migrations.AlterField(
            model_name='pest',
            name='common_name',
            field=models.CharField(default='Unknown Pest', help_text='Common name of the pest', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='common_name',
            field=models.CharField(default='Unknown Disease', help_text='Common name of the disease', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='common_name',
            field=models.CharField(default='Unknown Plant', help_text='Primary common name', max_length=150),
        ),
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(default='Unknown Species', help_text='Unique scientific name (Genus species)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='seed_name',
            field=models.CharField(default='Unknown Seed', help_text="Specific seed name, often includes variety (e.g., 'Beefsteak Tomato Seeds')", max_length=150),
        ),
        migrations.AlterField(
            model_name='companionplantinginteraction',
            name='interaction_code',
            field=models.CharField(default='DEFAULT_CODE', help_text='Unique code, e.g., PEST_REPEL_APHID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='companionplantinginteraction',
            name='interaction_type',
            field=models.CharField(choices=[('BEN', 'Beneficial'), ('DET', 'Detrimental'), ('NEU', 'Neutral')], default='NEU', help_text='Type of interaction (beneficial, detrimental, neutral)', max_length=3),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='entity_type',
            field=models.CharField(default='plant', help_text="Type of entity being contributed (e.g., 'plant', 'seed', 'tip')", max_length=50),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='proposed_data',
            field=models.JSONField(default=dict, help_text='JSON data containing the proposed changes or additions'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the contribution', max_length=20),
        ),
    ]
